### ISSUE TITLE
Coverage report

### ISSUE THREAD

**Issue by king-of-knightss** [chiselverify/chiselverify#44]
Could you please tell me how to get **code coverage**? I have read the paper you published and also studied the examples you gave in the source code. 
![code coverage](https://user-images.githubusercontent.com/61646108/175103492-181ac4a3-ad29-423b-b67c-336181c3d266.png)
It looks like there is just a picture in the paper, but no specific method is pointed out in the documentation or an example given in the source code?

**Comment by Dobios** [comment]
@king-of-knightss This is done using the line coverage plugin that was added to Treadle (https://github.com/chipsalliance/treadle/pull/263).  
It can be enabled by passing the `EnableCoverage` annotation to Treadle.  
The best info about this can be found [in the PR itself](https://github.com/chipsalliance/treadle/pull/263#issuecomment-726085050).  
Note that Treadle has changed quite a bit since then, and different solutions have been implemented to obtain line coverage of the FIRRTL description. The main goal was to provide a workable solution for line-coverage, which at the time wasn't supported by the simulator, this has since changed with the introduction of the `cover` statement at the Chisel level.

I hope that this helps!

**Comment by king-of-knightss** [comment]
Thanks a lot for your help! But here are also some questions.

I found the usage example you mentioned about code coverage in [CoverageTest.scala](https://github.com/chipsalliance/treadle/blob/master/src/test/scala/treadle/CoverageTest.scala).
It can indeed generate relevant data on code coverage, but it seems that when using it, the TreadleTester must be called through the following statement
`val tester = TreadleTester(Seq(FirrtlSourceAnnotation(testFirrtl), EnableCoverageAnnotation))`
At the same time, the firrtl file of the hardware circuit must be generated in advance as the input of TreadleTester.

If I want to complete the code coverage test by introducing parameters or turning on some switches based on this set of functional coverage tests ([functional coverage tests](https://github.com/chiselverify/chiselverify/blob/master/src/test/scala/examples/ArbiterTest.scala)), what should I do?
